# Import pydantic to help define structure (models) for our data
import pydantic

# Data structure representing a PDF split into chunks with its source ID
class RAGChunkAndSrc(pydantic.BaseModel):
    # A list of text paragraphs (chunks) from the PDF
    chunks: list[str]
    # The name or ID of the PDF file (optional)
    source_id: str = None

# Data structure representing the result of uploading to the database
class RAGUpsertResult(pydantic.BaseModel):
    # The number of paragraphs successfully uploaded (ingested)
    ingested: int

# Data structure representing search results from the database
class RAGSearchResult(pydantic.BaseModel):
    # A list of matching text paragraphs found
    contexts: list[str]
    # A list of source file paths where the text was found
    sources: list[str]

# Data structure representing the final answer generated by the AI
class RAGQueryResult(pydantic.BaseModel):
    # The written answer from the AI
    answer: str
    # A list of files the AI referenced to get the answer
    sources: list[str]
    # How many paragraphs were used to construct the answer
    num_contexts: int
